## Enhanced scoring threshold for more accurate suspicious moment detection
alert_threshold: 4

## Optimized confidence thresholds for better accuracy
phone_conf: 0.45

## Class label order used by the detector; change to match your trained model
classes:
  - person
  - phone
  - book
  - earphone
  - calculator

## Optimized weights for accurate suspicious moment detection (tune per exam policy)
weights:
  phone: 5               # phone detected with conf >= phone_conf
  earphone: 4            # earphones detected
  person: 5              # another person detected
  book: 3                # book/paper detected when not allowed
  calculator: 3          # calculator detected when not allowed
  notebook: 0            # laptop/notebook presence (0 to disable)
  # monitor: 0             # external monitor/TV presence (0 to disable)
  gaze_off_per_sec: 1    # per-second weight once off-screen gaze exceeds threshold
  repetitive_head: 2     # repetitive head movement within window

## Allowed items; set true to ignore their detections in scoring
allow_book: false
allow_calculator: false

## Optimized gaze monitoring for better performance
gaze_duration_threshold: 3.0

## Repetitive head movement parameters
repeat_dir_threshold: 3    # N same-direction turns within window (increased for accuracy)
repeat_window_sec: 15.0    # seconds window to evaluate repetition (increased)

## Enhanced detector settings for performance optimization
# Primary YOLO model (name or path), e.g., yolo11m.pt
detector_primary: yolo11m.pt
# Secondary custom YOLO weights path
detector_secondary: models/model_bestV3.pt
# Optimized confidence threshold for faster processing
detector_conf: 0.35
# Merge overlapping boxes from both models (IoU-based NMS)
detector_merge_nms: true
detector_nms_iou: 0.4

## Enhanced merge strategy: 'wbf' (weighted box fusion) for better accuracy
detector_merge_mode: wbf

## Per-class confidence thresholds for more accurate detection
class_conf:
  phone: 0.45
  earphone: 0.40
  smartwatch: 0.45
  person: 0.50
